apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: qkafka-knative-consumer
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/target: "1"
        spec:
          container:
            image: docker.io/burrsutter/qkafka-knative-consumer:1.0.1
            resources:
              requests: 
                memory: "50Mi" 
                cpu: "75m" 
              limits:
                memory: "50Mi"
                cpu: "75m" 
            livenessProbe:
              httpGet:
                path: /
            readinessProbe:
              httpGet:
                path: /