apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: qkafkaproducer
  name: qkafkaproducer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qkafkaproducer
  template:
    metadata:
      labels:
        app: qkafkaproducer
    spec:
      containers:
      - name: qkafkaproducer
        image: docker.io/burrsutter/qkafkaproducer:1.0.2
        imagePullPolicy: Always # because I am in development-mode
        env:
        - name: MP_MESSAGING_OUTGOING_MYSTREAM_BOOTSTRAP_SERVERS
          value: burr-cluster-kafka-bootstrap:9092
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "60Mi" 
            cpu: "250m" 
          limits:
            memory: "60Mi"
            cpu: "250m" 