apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: qwebsockets2kafka
  name: qwebsockets2kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwebsockets2kafka
  template:
    metadata:
      labels:
        app: qwebsockets2kafka
    spec:
      containers:
      - name: qwebsockets2kafka
        image: docker.io/burrsutter/qwebsockets2kafka:1.0.1
        imagePullPolicy: Always # because I am in development-mode
        env:
        - name: MP_MESSAGING_OUTGOING_MYSTREAM_BOOTSTRAP_SERVERS
          value: burr-cluster-kafka-bootstrap:9092
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "100Mi" 
            cpu: "250m" 
          limits:
            memory: "100Mi"
            cpu: "250m" 
        livenessProbe:
          httpGet:
              port: 8080
              path: /
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 2          
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3
