apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: qkafkaconsumer
  name: qkafkaconsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qkafkaconsumer
  template:
    metadata:
      labels:
        app: qkafkaconsumer
    spec:
      containers:
      - name: qkafkaconsumer
        image: docker.io/burrsutter/qkafkaconsumer:1.0.1
        imagePullPolicy: Always # because I am in development-mode        
        ports:
          - containerPort: 8081
        resources:
          requests: 
            memory: "40Mi" 
            cpu: "250m" 
          limits:
            memory: "40Mi"
            cpu: "250m" 
