apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: qkafkaconsumer
  name: qkafkaconsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qkafkaconsumer
  template:
    metadata:
      labels:
        app: qkafkaconsumer
    spec:
      containers:
      - name: qkafkaconsumer
        image: docker.io/burrsutter/qkafkaconsumer:1.0.2
        imagePullPolicy: Always # because I am in development-mode
        env:
        - name: MP_MESSAGING_INCOMING_INPUT_BOOTSTRAP_SERVERS
          value: hello-cluster-kafka-external-bootstrap:9094
#          value: hello-cluster-kafka-bootstrap-franz.apps.one.burr.in
        ports:
          - containerPort: 8081
        resources:
          requests: 
            memory: "60Mi" 
            cpu: "250m" 
          limits:
            memory: "100Mi"
            cpu: "250m" 
